credentials:
  usernames:
    sai:
      email: sai@gmail.com
      failed_login_attempts: 0 
      logged_in: False 
      name: Sai
      password: sai@0112

  
cookie:
  expiry_days: 1000
  key: some_signature_key 
  name: some_cookie_name
pre-authorized:
  emails:
  - sairoxx1990@gmail.com