[theme]
base = "dark"
primaryColor = "#6D28D9"
backgroundColor = "#0F172A"
secondaryBackgroundColor = "#1E293B"
textColor = "#E2E8F0"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "auto"
showErrorDetails = true

[runner]
fastReruns = true

[mapbox]
token = ""

[ui]
customCSS = """
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap');

    /* Global Styles */
    html, body, [class*="css"] {
        font-family: 'Poppins', sans-serif;
        color: #E2E8F0;
    }

    /* Main content area */
    .main .block-container {
        padding-top: 2rem;
        padding-bottom: 2rem;
        background: linear-gradient(135deg, #0F172A 0%, #1E293B 100%);
        border-radius: 20px;
        box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37);
    }

    /* Sidebar */
    .css-1d391kg {
        background-color: #1E293B;
        border-right: 1px solid #2D3748;
        padding: 2rem 1rem;
    }

    /* Headers */
    h1, h2, h3, h4, h5, h6 {
        color: #F1F5F9;
        font-weight: 600;
        letter-spacing: -0.02em;
    }

    /* Buttons */
    .stButton>button {
        background: linear-gradient(45deg, #6D28D9, #8B5CF6);
        color: #FFFFFF;
        border: none;
        border-radius: 8px;
        padding: 0.5rem 1rem;
        font-weight: 600;
        transition: all 0.3s ease;
        box-shadow: 0 4px 12px rgba(139, 92, 246, 0.3);
    }
    .stButton>button:hover {
        transform: translateY(-2px);
        box-shadow: 0 6px 20px rgba(139, 92, 246, 0.4);
    }
    .stButton>button:active {
        transform: translateY(0px);
    }

    /* Text inputs */
    .stTextInput>div>div>input {
        background-color: #2D3748;
        color: #E2E8F0;
        border: 1px solid #4A5568;
        border-radius: 8px;
        padding: 0.5rem 1rem;
        transition: all 0.3s ease;
    }
    .stTextInput>div>div>input:focus {
        border-color: #6D28D9;
        box-shadow: 0 0 0 2px rgba(109, 40, 217, 0.2);
    }

    /* Select boxes */
    .stSelectbox>div>div>select {
        background-color: #2D3748;
        color: #E2E8F0;
        border: 1px solid #4A5568;
        border-radius: 8px;
        padding: 0.5rem 1rem;
        transition: all 0.3s ease;
    }
    .stSelectbox>div>div>select:focus {
        border-color: #6D28D9;
        box-shadow: 0 0 0 2px rgba(109, 40, 217, 0.2);
    }

    /* Sliders */
    .stSlider>div>div>div>div {
        background-color: #6D28D9;
    }
    .stSlider>div>div>div>div>div {
        background-color: #8B5CF6;
        transition: all 0.3s ease;
    }
    .stSlider>div>div>div>div>div:hover {
        transform: scale(1.1);
    }

    /* Metrics */
    .css-1xarl3l {
        background-color: #2D3748;
        border: 1px solid #4A5568;
        border-radius: 8px;
        padding: 1rem;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
        transition: all 0.3s ease;
    }
    .css-1xarl3l:hover {
        transform: translateY(-4px);
        box-shadow: 0 8px 24px rgba(0, 0, 0, 0.15);
    }

    /* DataFrames */
    .dataframe {
        border: none;
        border-collapse: separate;
        border-spacing: 0;
        border-radius: 8px;
        overflow: hidden;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
    }
    .dataframe th {
        background-color: #2D3748;
        color: #F1F5F9;
        font-weight: 600;
        padding: 0.75rem 1rem;
        text-align: left;
    }
    .dataframe td {
        background-color: #1E293B;
        color: #E2E8F0;
        padding: 0.75rem 1rem;
        border-top: 1px solid #4A5568;
    }
    .dataframe tr:hover td {
        background-color: #2D3748;
    }

    /* Plots */
    .js-plotly-plot {
        border-radius: 8px;
        overflow: hidden;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
    }

    /* Tooltips */
    .stTooltipIcon {
        color: #8B5CF6;
        transition: all 0.3s ease;
    }
    .stTooltipIcon:hover {
        color: #6D28D9;
        transform: scale(1.1);
    }

    /* Scrollbar */
    ::-webkit-scrollbar {
        width: 8px;
        height: 8px;
    }
    ::-webkit-scrollbar-track {
        background: #1E293B;
    }
    ::-webkit-scrollbar-thumb {
        background: #4A5568;
        border-radius: 4px;
    }
    ::-webkit-scrollbar-thumb:hover {
        background: #6D28D9;
    }
"""